defaults = {
	'preview': True,
	'bounds': True,
	'pipes': False,
	'amount': 40,
	'width': 1.0,
	'height': 2.0,
	'length_x': 0.5,
	'length_y': 0.5,
	'straight': 40,
	'decoration': 30,
	'rail': 40,
	'split': 30,
	'bevel': 35,
}
