defaults = {
	'amount': 20,
	'width': 1.0,
	'height': 2.0,
	'depth': 0.5,
	'uniform': False,
	'length_x': 0.5,
	'length_y': 0.5,
	'min': 0.01,
	'max': 0.05,
	'straight': 40,
	'decoration': 30,
	'rail': 40,
	'split': 30,
	'bevel': 35,
	'surface': 2,
	'seed': 0,
	'convert': False,
	'create_empty': False,
	'hide_lines': True,
}
